### ISSUE TITLE
Incorrect validation of mixed-type arrays

### ISSUE THREAD

**Issue by EdwardSalter** [jormaechea/open-api-mocker#41]
I am receiving an error from open-api-mocker when attempting to pass a request body that contains a parameter that is defined as array with items that are either a string or number.
The definition looks nearly identical to the example from the OpenAPI website:
```yaml
# ["foo", 5, -2, "bar"]
type: array
items:
  oneOf:
    - type: string
    - type: integer
```

When attempting to send a request where the value of this parameter is defined like this:
```json
 [1, 3, ">=5"]
```
open-api-mocker is responding with the following:
```json
{
  "errors": [
    "Invalid request body: 'filters[0]' should be object"
  ]
}
```

I have done some debugging myself and have found that somewhere along the lines, the schema read from file is not quite what is sent through to `ajv` to do the validation.
I am not familiar with `superstruct` but I believe that it is it's use in [lib/components/structs/schema.js](https://github.com/jormaechea/open-api-mocker/blob/master/lib/components/schemas/structs.js) that is causing the schema to become 'mangled' (I hesitate to say invalid since it passes the schema but messes up the intention).
Without knowing how `superstruct` works, I am guessing that [this block of code](https://github.com/jormaechea/open-api-mocker/blob/5d34047d473ef76af0560123d3062e942fc88379/lib/components/schemas/structs.js#L53) acts as a default object and incoming data gets assigned over the top of it.
Since the `items` property is defined as `items: struct.lazy(() => struct.optional(referenceUnion(SchemaStruct))),` (i.e. a Reference or a Schema`, it validates against the same structure being defined in this file.
This means that it uses the same default object which puts in an additional `type: object`.
This means the input schema above:
```yaml
type: array
items:
  oneOf:
    - type: string
    - type: integer
```
suddenly turns into this:
```yaml
type: array
items:
  type: object
  # other default properties put in by superstruct default
  oneOf:
    - type: string
    - type: integer
```
Whilst this is potentially valid in terms of the OpenAPI specification (I haven't checked using some other tool), it makes no sense since the array items can't be of type object and also use the `anyOf, oneOf, allOf` keywords as well.

My initial thought on a fix would be to just remove the type from the default object but I have no idea on what other kind of effects that have.
