### ISSUE TITLE
Generating incrementing numbers in an array

### ISSUE THREAD

**Issue by kubijo** [jormaechea/open-api-mocker#46]
I was (unsuccessfully) trying to find if there's an option to generate incremental numbers that could be used in array values (be it an object or number literal directly)… essentially what you can do [with counters in CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters).

Are you aware of a way to achieve / implement that?

**Comment by jormaechea** [comment]
Hi @kubijo. I'm afraid there's not such feature implemented right now.

Could you elaborate more on a practical example where this would be useful?

Thanks!

**Comment by kubijo** [comment]
I'm implementing an API mock that has several lists of identities a there are logical links between them.
If I could use something like an `$index` placeholder for filling in the IDs, I'd be able to ensure the links just by having correct lists lengths.

**Comment by jormaechea** [comment]
Hi @kubijo, sorry for the delays.

Every extension to the OpenAPI specification should be made by adding `x-` prefixed properties.

One solution that comes to my mind would be to add a `x-index-property: someProperty` to your `array`s, and then add support for this in the response generator.

For example:

```yaml
MySchema:
  type: array
  x-index-property: index
  x-count: 2
  items:
    type: object
    properties:
      name:
        type: string
        x-faker: name.findName
```

This would generate a response like this:

```json
[{
  "name": "John Doe",
  "index": 0
},
{
  "name": "Jane Doe",
  "index": 1
}]
```

What do you think?
