### ISSUE TITLE
mock improvements suggestions

### ISSUE THREAD

**Issue by alessandroperetti** [jormaechea/open-api-mocker#76]
Hi all,
I don't know if what I am asking is already present but I don't think so.

Could be helpful having a randomize string between a well defined array list. 

For example inside openapi yaml something like this:

`custom-mock: chooseOneBetween('string1', string2', 'string3')`

Maybe is already implemented but googling I didn't find any solution.

Thanks,

A

**Comment by alessandroperetti** [comment]
I got a solution for the question above checking the source code:
for example, in openapi yaml:
``` 
someData:
    type: string
    enum:
    - string1
    - string2
    - string3
    - string4
```
Open api mocker automatically checks for the prop `enum` and if present it performs `faker.helpers.arrayElement(enumOptions);` 

where enumOptions are the options listed under the enum property above.

I hope it helps.

A
